# Generated by Django 3.0.4 on 2020-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0002_auto_20200422_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begarduser',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
