# Generated by Django 3.0.4 on 2020-04-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0004_userfollowing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user_id', 'following_user_id')},
        ),
    ]
