# Generated by Django 3.0.4 on 2020-03-26 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='begard_app.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='begard_app.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecreationalPlace',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='begard_app.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='begard_app.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='begard_app.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BegardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
