# Generated by Django 3.0.4 on 2020-03-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='begarduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecreationalPlace',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlace',
            fields=[
                ('place_id', models.CharField(default='none', max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('address', models.TextField(default='Nothing')),
                ('photo_ref', models.TextField(default='Nothing')),
                ('lng', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.City')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
