# Generated by Django 3.0.4 on 2020-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='begarduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
