# Generated by Django 3.0.4 on 2020-04-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='finish_day',
            new_name='finish_date',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='start_day',
            new_name='start_date',
        ),
    ]
