# Generated by Django 3.0.4 on 2020-03-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPlace',
            new_name='TouristAttraction',
        ),
    ]
