# Generated by Django 3.0.4 on 2020-03-29 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0002_cafe_comment_plan_planitem_shoppingmall'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='like_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), null=True, size=None),
        ),
    ]
